### ISSUE TITLE
about eval_UDA.py

### ISSUE THREAD

**Issue by jdg900** [valeoai/MTAF#5]
Thanks for sharing your codes.

I was impressed with your good research.

Could you explain why the output map is not resized for target size(cfg.TEST.OUTPUT_SIZE_TARGET) in the case of Mapillary dataset in line 57 of eval_UDA.py? 

When I tested the trained model on Mapillary dataset, inference took a long time due to the large resolution.

I'm looking forward to hearing from you.

Thank you!

**Comment by SportaXD** [comment]
Thank you for bringing this issue to our attention.

The Mapillary labels should be resized in the dataloader but the default behavior was incorrect during inference. The last commit should fix your problem.

Please let us know if you face more issues with the code.

Thank you!
