### ISSUE TITLE
About 'the multi-target baseline'

### ISSUE THREAD

**Issue by liwei1101** [valeoai/MTAF#8]
Thank you for sharing the code for your excellent work. I have some basic questions about your implementation.

```
d_main = get_fc_discriminator(num_classes=num_classes)
d_main.train()
d_main.to(device)
d_aux = get_fc_discriminator(num_classes=num_classes)
d_aux.train()
d_aux.to(device)
```

Can you tell me why the multi-domain baseline code does not use multiple discriminators but only one discriminator. 
It looks like a single domain approach. 
Thanks！

**Comment by SportaXD** [comment]
As explained in the paper, the "multi-target baseline" is the naive approach in which we consider the fusion of all target domains as a single target domain, which can then be used in a single target domain UDA approach. Thus, you're intuition is correct.
