### ISSUE TITLE
About MTKT code

### ISSUE THREAD

**Issue by liwei1101** [valeoai/MTAF#9]
In train_UDA.py 
758 line
```python
        d_main_list[i] = d_main
        optimizer_d_main_list.append(optimizer_d_main)
        d_aux_list[i] = d_aux
        optimizer_d_aux_list.append(optimizer_d_aux)
```
If this were done（d_main_list[i] = d_main and d_aux_list[i] = d_aux）, it would make all the discriminators in the list use the same one, shouldn't there be one discriminator for each classifier?

**Comment by SportaXD** [comment]
You're right, there was a bug when AMP was not used (i.e. when cfg.TRAIN.AMP is False). I fixed the code.
